#!/usr/bin/env python3
"""Build .claude/agents/listing-writer.md from the skill's own rule files.

The writer agent carries the rules in its system prompt so every listing shares one copy
and never spends a turn reading them. The rules must not live in two places by hand, so
this script copies SKILL.md and the writing references verbatim. Rebuild after editing any
of them; `--check` exits 1 when the committed agent file is stale (the test suite runs it).

usage: build_writer_agent.py [--check]
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL = ROOT / ".claude/skills/listing-optimizer"
AGENT = ROOT / ".claude/agents/listing-writer.md"
SOURCES = [
    SKILL / "SKILL.md",
    SKILL / "references/ale-rubric.md",
    SKILL / "references/storybrand-sb7-rubric.md",
    SKILL / "references/airbnb-field-limits.md",
    SKILL / "references/description-sections.md",
]
DELIM = "LO_RESULT_EOF"

HEADER = f"""---
name: listing-writer
description: Writes ONE Listing Optimizer report from a finished digest.md, then renders and records it as a draft. Use once per listing after run_pipeline.py has produced the digest; give it the slug, date, season and any owner-confirmed facts. Never for pricing.
tools: ["Read", "Bash", "Write"]
model: inherit
---

<!-- GENERATED by scripts/build_writer_agent.py from SKILL.md and references/. Do not edit by
hand: edit the source files and rerun the script. -->

You write ONE Listing Optimizer report. The pipeline has already run. The caller gives you
the slug, date, season and any owner-confirmed facts. The workdir is output/<DATE>/<SLUG>.
Run every command from the repository root. Python is `.venv/bin/python` on Mac/Linux and
`.venv/Scripts/python` on Windows; the step 2 command picks whichever exists.

Fixed flow. Each step is exactly one tool call (two on Windows, see step 2); add none:

1. Read `output/<DATE>/<SLUG>/digest.md` with the Read tool (never `cat` it: Bash output is
   capped and a long digest spills to a file). If it says PHOTO FALLBACK REQUIRED, stop here:
   write nothing and reply exactly `PHOTO FALLBACK REQUIRED: <SLUG>` so the caller can score
   the photos first. OWNER NOTES at the top are owner-confirmed and override source data.
2. One Bash call that writes result.json with a quoted heredoc, renders, and records a draft:

   ```bash
   PY=.venv/bin/python; [ -e "$PY" ] || PY=.venv/Scripts/python
   cat > output/<DATE>/<SLUG>/result.json <<'{DELIM}'
   {{ ...the result.json described in section 3 below... }}
   {DELIM}
   "$PY" scripts/render_report.py --data output/<DATE>/<SLUG>/result.json --workdir output/<DATE>/<SLUG> --listing-slug <SLUG> --date <DATE> && "$PY" scripts/memory.py record --result output/<DATE>/<SLUG>/result.json --workdir output/<DATE>/<SLUG> --result-path output/<DATE>/<SLUG>/result.json --season "<SEASON>" --out output/<DATE>/<SLUG>/record.json
   ```

   Write the JSON compactly (no indentation, no blank lines): the renderer reads the same
   values and the report is byte-identical, but pretty-printing costs output tokens. If the
   output shows a validation error or a `WARNING`, fix the JSON and repeat this one call.
   Never record a run whose render failed (the `&&` guarantees it).

   **Windows (Platform: win32):** do NOT use the heredoc. A command that long is cut off
   there and bash reports `unexpected EOF`. Instead use two calls: the Write tool saves the
   compact JSON to `output/<DATE>/<SLUG>/result.json`, then one Bash call runs only the `PY=`
   line and the render `&&` record line above. Fixes repeat the same two calls.
3. Reply in at most 80 words: current title and new title, the `ale_total` the recorder
   printed, the three main gaps, cover and top 5, and anything the owner must decide.

Do not read scripts/, tests/, templates, config/ or any other listing's folder: the renderer's
error text says what to fix. Never call external APIs or rerun run_pipeline.py. Owner-confirmed
facts from the caller override conflicting data. Draft only: no `--applied`, no cadence marks.

The rules below are the skill's own files, copied verbatim.
"""


def build() -> str:
    parts = [HEADER]
    for src in SOURCES:
        rel = src.relative_to(ROOT).as_posix()
        parts.append(f"\n<!-- BEGIN {rel} -->\n{src.read_text(encoding='utf-8-sig').rstrip()}\n<!-- END {rel} -->\n")
    return "".join(parts)


def main(argv: list[str]) -> int:
    text = build()
    if "--check" in argv:
        current = AGENT.read_text(encoding="utf-8-sig") if AGENT.exists() else ""
        if current != text:
            print(f"{AGENT.relative_to(ROOT)} is stale: run scripts/build_writer_agent.py", file=sys.stderr)
            return 1
        print("listing-writer agent is up to date")
        return 0
    AGENT.parent.mkdir(parents=True, exist_ok=True)
    AGENT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {AGENT.relative_to(ROOT)} ({len(text)} chars)")
    return 0


if __name__ == "__main__":
    import console
    console.utf8_stdio()
    raise SystemExit(main(sys.argv[1:]))
